version: '3'

services:
  django:
    build: .
    container_name: sec_shop_django
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    environment:
      - DJANGO_SETTINGS_MODULE=security_shop.settings
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=pgdb
      - DB_PORT=5432
    volumes:
      - .:/usr/src/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - pgdb

  pgdb:
    image: postgres:17
    container_name: sec_shop_pgdb
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: sec_shop_redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

volumes:
  pgdbdata:
  redisdata: